<?php return ; ?>

[App]
dashboardTitle          = "Basit Stok Yönetimi"
softwareType            = "development"
url                     = "http://localhost/okulProje/"
imgUrl                  = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/defaultImages/"
upDir                   = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/upload/siparis/"
hmzPatDir               = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/upload/180b863d0b2950bbb02f862062003a6f/"
patternDir              = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/upload/kDSMla0yrk8eqz6K4jAz/"
fileDir                 = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/upload/kDSMla0yrk8e6qzK4jAz/"
stfDir                  = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/upload/6K4jAzkDSMla0yrk8eqz/"
suppliesFileDir         = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/upload/12859hlkui4378d6538784df2c02e51s/"
classDir                = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/core/classes/"
coreDir                 = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/core/"
dbDir                   = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/core/database/"
dbTableDir              = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/core/database/databaseTables/"
modulesDir              = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/modules/"
integrationDir          = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/integration/"
libraryDir              = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/library/"
helpersDir              = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/core/helpers/"
templateFileDir         = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/templates/"
templatePath            = "http://localhost/okulProje/templates/"
SMARTY_SYSPLUGINS_DIR   = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/core/smarty/sysplugins/"
SMARTY_PLUGINS_DIR      = "/Applications/XAMPP/xamppfiles/htdocs/okulProje/core/smarty/plugins/"
TIME_FORMAT             = "d-m-Y"
IMAGE_RESIZE            = "TRUE"
MAX_FILES_SIZE          = "10485760"